
version: '2'

services:

  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 749
    volumes:
      - portainer_data:/var/lib/docker/volumes
      - /var/run/docker.sock:/var/run/docker.sock
#--------------------------------------------------------------------------
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - 631
    environment:
      WORDPRESS_DB_HOST: mysql:542
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

    volumes:
      - mysql:/var/lib/mysql
#------------------------------------------------------------------

volumes:
  wordpress:
  mysql:
  portainer_data:

