version: '2'

services:
   
   mysql:
        image: mysql:latest
        container_name: mysql
        restart: always
        environment:
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
            MYSQL_ROOT_PASSWORD: wordpress
            MYSQL_DATABASE: wordpress
        volumes:
            - mysql:/var/lib/mysql

volumes:
    mysql:
