
version: '2'

services:

  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
       - 9000:9000
    volumes:
      - portainer_data:/var/lib/docker/volumes
      - /var/run/docker.sock:/var/run/docker.sock
#--------------------------------------------------------------------------

   

#--------------------------------------------------------------------------
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
        - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
#-------------------------------------------------------------------------
  mysql:
    image: mysql:5.7
    restart: always
    environment:
        MYSQL_DATABASE: wordpress
        MYSQL_USER: wordpress
        MYSQL_PASSWORD: wordpress
        MYSQL_RANDOM_ROOT_PASSWORD: wordpress

    volumes:
      - mysql:/var/lib/mysql
#-------------------------------------------------------------------------

volumes:
  wordpress:
  mysql:
  portainer_data:
