version: '2'

services:
    
    nginx:
        image: nginx:latest
        container_name: nginx
        restart: always
        ports:
            - "8080:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/nginx.conf


    mysql:
        image: mysql:latest
        container_name: mysql
        restart: always
        environment:
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
            MYSQL_ROOT_PASSWORD: wordpress
            MYSQL_DATABASE: wordpress
        volumes:
            - mysql:/var/lib/mysql

    phpmyadmin:
        depends_on:
            - mysql
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: wordpress
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        ports:
            - 8000:80

    wordpress:
        depends_on:
            - mysql
            - phpmyadmin
        image: wordpress:latest
        container_name: wordpress
        restart: always
        ports:
            - 8000:80
        environment:
            WORDPRESS_DB_HOST: mysql:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
        networks:
            - wpsite
        volumes:
            - wordpress:/var/www/html
            - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini

    
volumes:
    mysql:
    wordpress:
