version: '2'

services:
   
    mysql:
        image: mysql:latest
        container_name: mysql
        restart: always
        environment:
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
            MYSQL_ROOT_PASSWORD: wordpress
            MYSQL_DATABASE: wordpress
        volumes:
            - mysql:/var/lib/mysql

    phpmyadmin:
        depends_on:
            - mysql
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: wordpress
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        ports:
            - 8080:80
    
volumes:
    mysql:
